<a href="https://colab.research.google.com/github/sapienology/First-Repo/blob/main/Is%20bestsller%20dataset%20sgd%20regressor%20model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import pandas as pd
import numpy as np

In [114]:
df1 = pd.read_csv('/content/amazon_products_sales_data_uncleaned.csv')

In [115]:
df1.head()

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29

In [116]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  object
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  30926 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

Bought in last month Column

In [117]:
df1['bought_in_last_month'].unique()

array(['300+ bought in past month', '6K+ bought in past month',
       '2K+ bought in past month', '10K+ bought in past month',
       '100K+ bought in past month', nan, '100+ bought in past month',
       '1K+ bought in past month', '500+ bought in past month',
       '80K+ bought in past month', '70K+ bought in past month',
       '50K+ bought in past month', '40K+ bought in past month',
       '60K+ bought in past month', '20K+ bought in past month',
       '30K+ bought in past month', '9K+ bought in past month',
       '50+ bought in past month', '5K+ bought in past month',
       'List Price:', '7K+ bought in past month',
       '4K+ bought in past month', 'Typical:',
       '200+ bought in past month', '8K+ bought in past month',
       'ESRB Rating: Everyone', '3K+ bought in past month',
       'No featured offers available', 'List:',
       'ESRB Rating: Rating Pending', '900+ bought in past month',
       '400+ bought in past month', '700+ bought in past month',
       'This product is certified by Amazon to work with Alexa. This product can be controlled with your voice through Alexa-enabled devices such as Amazon Echo and Amazon Tap.',
       '800+ bought in past month', 'More Buying Choices',
       '600+ bought in past month', '($1,999.75$1,999.75/100 cm)',
       'Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.',
       'ESRB Rating: Everyone 10+', 'ESRB Rating: Adults Only',
       '($54.26$54.26/count)', 'New Price:', '($1,315.78$1,315.78/kg)',
       'Alexa Built-in devices let you talk directly to Alexa, allowing you to play music, control your smart home, get news, weather, and more using your voice.',
       '($4,813.00$4,813.00/100 cm)', '($433.33$433.33/count)',
       '($252.00$252.00/count)', '($1,080.00$1,080.00/kg)',
       '($46.81$46.81/oz)', '($828.56$828.56/kg)', '($53.33$53.33/count)',
       '($30.00$30.00/count)', '($766.33$766.33/in)',
       '90K+ bought in past month', '($2.18$2.18/count)',
       '($5.27$5.27/in)', '($179.99$179.99/count)', '($43.69$43.69/oz)',
       'Was:'], dtype=object)

In [118]:
lowered = df1['bought_in_last_month'].astype(str).str.lower()
lowered = lowered.str.replace(',', '', regex=False)

numbers = pd.to_numeric(lowered.str.extract(r'(\d+\.?\d*)')[0],
                        errors = 'coerce')
multiplier = np.where(lowered.str.contains('k') , 1000 ,1)

df1['bought_in_last_month'] = (numbers * multiplier).round().astype('Int64')

In [119]:
df1 = df1.dropna(subset = ['bought_in_last_month'])

In [120]:
df1.isna().sum()

title                           0
rating                         93
number_of_reviews              93
bought_in_last_month            0
current/discounted_price     6927
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability         8663
delivery_details             6894
sustainability_badges       29491
image_url                       0
product_url                  2067
collected_at                    0
dtype: int64

Rating COlumn

In [121]:
df1['rating'] = df1['rating'].astype(str).str.extract(r'(\d+\.?\d*)')[0]

In [122]:
df1['rating'] = df1['rating'].astype(float)

In [123]:
df1['rating'] = df1['rating'].fillna(df1['rating'].mean())

Image_Url Column

In [124]:
df1['is_best_seller']

0           No Badge
1           No Badge
2           No Badge
3        Best Seller
4           No Badge
            ...
42670       No Badge
42671       No Badge
42672       Save 18%
42673       No Badge
42674       No Badge
Name: is_best_seller, Length: 32233, dtype: object

In [125]:
df1['is_best_seller'].unique()

array(['No Badge', 'Best Seller', "Amazon's", 'Limited time deal',
       'Save 30%', 'Save 12%', 'Save 17%', 'Ends in', 'Save 18%'],
      dtype=object)

In [126]:
from sklearn.preprocessing import LabelEncoder

In [127]:
le = LabelEncoder()

In [128]:
df1['is_best_seller'] = le.fit_transform(df1['is_best_seller'])

In [129]:
df1['is_best_seller'] = df1['is_best_seller'].astype(int)

Is Sponsored Column

In [130]:
df1['is_sponsored'].unique()

array(['Sponsored', 'Organic'], dtype=object)

In [131]:
df1['is_sponsored'] = df1['is_sponsored'].replace({'Sponsored' : 0 ,
                                                 'Organic' :1  })

/tmp/ipykernel_15028/1451240710.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['is_sponsored'] = df1['is_sponsored'].replace({'Sponsored' : 0 ,

In [132]:
df1['is_sponsored'] = df1['is_sponsored'].astype(int)

Is Couponed Column

In [133]:
df1['is_couponed'].unique()

array(['Save 15%  with coupon', 'No Coupon', 'Save $10.00  with coupon',
       'Save 10%  with coupon', 'Save $20.00  with coupon',
       'Save $4.00  with coupon', 'Save $0.33  with coupon',
       'Save $18.00  with coupon', 'Save 5%  with coupon',
       'Save $2.00  with coupon', 'Save $15.00  with coupon',
       'Save 6%  with coupon', 'Save $8.00  with coupon',
       'Save $40.00  with coupon', 'Save $1.50  with coupon',
       'Save 7%  with coupon', 'Save 20%  with coupon',
       'Save $1.00  with coupon', 'Save $5.00  with coupon',
       'Save $30.00  with coupon', 'Save $12.00  with coupon',
       'Save 25%  with coupon', 'Save $133.00  with coupon',
       'Save $50.00  with coupon', 'Save $11.00  with coupon',
       'Save 30%  with coupon', 'Save 50%  with coupon',
       'Save $3.00  with coupon', 'Save 40%  with coupon',
       'Save $25.00  with coupon', 'Save $13.00  with coupon',
       'Save 25%  with coupon (some sizes/colors)',
       'Save 8%  with coupon', 'Save $69.00  with coupon',
       'Save $100.00  with coupon', 'Save $90.00  with coupon'],
      dtype=object)

In [134]:
df1['is_couponed'] = le.fit_transform(df1['is_couponed'])

In [135]:
df1['is_couponed'] = df1['is_couponed'].astype(int)

In [136]:
df1['is_couponed']

0        25
1         0
2         0
3         0
4         0
         ..
42670     0
42671    14
42672     0
42673     0
42674     0
Name: is_couponed, Length: 32233, dtype: int64

In [137]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32233 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     32233 non-null  object
 1   rating                    32233 non-null  float64
 2   number_of_reviews         32140 non-null  object
 3   bought_in_last_month      32233 non-null  Int64
 4   current/discounted_price  25306 non-null  object
 5   price_on_variant          32233 non-null  object
 6   listed_price              32233 non-null  object
 7   is_best_seller            32233 non-null  int64
 8   is_sponsored              32233 non-null  int64
 9   is_couponed               32233 non-null  int64
 10  buy_box_availability      23570 non-null  object
 11  delivery_details          25339 non-null  object
 12  sustainability_badges     2742 non-null   object
 13  image_url                 32233 non-null  object
 14  product_url               30166 non-null  object
 15  collected_at              32233 non-null  object
dtypes: Int64(1), float64(1), int64(3), object(11)
memory usage: 4.2+ MB

IMAGE URL

In [138]:
df1 = df1.drop('image_url' , axis = 1)

product url

In [139]:
df1 = df1.drop('product_url' , axis = 1)

Sustainabity badges

In [140]:
df1 = df1.drop('sustainability_badges' , axis = 1)

Collected at column

In [141]:
df1

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300,89.68,basic variant price: 2.4GHz,$159.00,4,0,25,Add to cart,"Delivery Mon, Sep 1",2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,"2,457",6000,9.99,basic variant price: nan,$15.99,4,0,0,Add to cart,"Delivery Fri, Aug 29",2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,"3,044",2000,314.00,basic variant price: nan,$349.00,4,0,0,Add to cart,"Delivery Mon, Sep 1",2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,"35,882",10000,NaN,basic variant price: $162.24,No Discount,1,1,0,NaN,NaN,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,"28,988",10000,NaN,basic variant price: $72.74,No Discount,4,1,0,NaN,NaN,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100,195.99,basic variant price: nan,No Discount,4,1,0,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200,89.99,basic variant price: $25.00 off coupon applied,No Discount,4,1,14,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",7,1,0,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,"7,102",500,10.39,basic variant price: nan,$15.98,4,1,0,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50,419.99,basic variant price: nan,$499.99,4,1,0,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",2025-08-30 19:56:33

In [142]:
df1 = df1.drop('collected_at' , axis = 1)

buy_box_availability

In [143]:
df1 = df1.drop('buy_box_availability' , axis = 1)

title

In [144]:
df1 = df1.drop('title' , axis = 1)

delivery_details

In [145]:
df1 = df1.drop('delivery_details' , axis = 1)

current/discounted_price

In [146]:
df1['current/discounted_price'].unique()

array(['89.68', '9.99', '314.00', ..., '35.96', '7.70', '20.14'],
      dtype=object)

In [147]:
df1['current/discounted_price'] = df1['current/discounted_price'].replace({',' , ''})

/tmp/ipykernel_15028/2831876563.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df1['current/discounted_price'] = df1['current/discounted_price'].replace({',' , ''})

In [148]:
df1['current/discounted_price'] = pd.to_numeric(df1['current/discounted_price'] , errors = 'coerce').astype(float)

In [149]:
df1['current/discounted_price'] = df1['current/discounted_price'].fillna(df1['current/discounted_price'].mean())

In [150]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32233 entries, 0 to 42674
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    32233 non-null  float64
 1   number_of_reviews         32140 non-null  object
 2   bought_in_last_month      32233 non-null  Int64
 3   current/discounted_price  32233 non-null  float64
 4   price_on_variant          32233 non-null  object
 5   listed_price              32233 non-null  object
 6   is_best_seller            32233 non-null  int64
 7   is_sponsored              32233 non-null  int64
 8   is_couponed               32233 non-null  int64
dtypes: Int64(1), float64(2), int64(3), object(3)
memory usage: 3.5+ MB

price_on_variant column

In [151]:
df1['price_on_variant'].unique()

array(['basic variant price: 2.4GHz', 'basic variant price: nan',
       'basic variant price: $162.24', ...,
       'basic variant price: $122.21', 'basic variant price: $206.71',
       'basic variant price: $112.96'], dtype=object)

In [152]:
df1['price_on_variant'] = df1['price_on_variant'].astype(str).str.lower()

df1['price_on_variant'] = df1['price_on_variant'].str.extract(r'(\d+\.?\d*)')
df1['price_on_variant'] = pd.to_numeric(df1['price_on_variant'] , errors = 'coerce').astype(float).round(4)

df1['price_on_variant'] = df1['price_on_variant'].fillna(df1['price_on_variant'].mean())

In [153]:
df1['price_on_variant']

0          2.400000
1        111.470333
2        111.470333
3        162.240000
4         72.740000
            ...
42670    111.470333
42671     25.000000
42672     30.000000
42673    111.470333
42674    111.470333
Name: price_on_variant, Length: 32233, dtype: float64

listed_price

In [154]:
df1['listed_price'].unique()

array(['$159.00', '$15.99', '$349.00', 'No Discount', '$19.98', '$14.33',
       '$17.99', '$21.89', '$20.00', '$48.99', '$19.99', '$38.98',
       '$14.39', '$169.99', '$29.99', '$219.99', '$15.00', '$24.99',
       '$32.72', '$71.87', '$18.99', '$21.44', '$199.99', '$99.95',
       '$49.99', '$33.99', '$39.99', '$89.99', '$119.97', '$35.64',
       '$24.58', '$69.99', '$249.99', '$27.99', '$6.29', '$239.99',
       '$229.99', '$169.00', '$32.29', '$34.99', '$348.00', '$65.99',
       '$5.84', '$176.99', '$96.99', '$11.87', '$43.29', '$64.99',
       '$159.95', '$45.79', '$109.99', '$8.99', '$32.99', '$149.99',
       '$25.99', '$99.99', '$35.99', '$449.00', '$76.99', '$165.00',
       '$13.33', '$7.79', '$30.00', '$129.99', '$79.99', '$22.99',
       '$78.00', '$719.00', '$299.89', '$175.00', '$299.99', '$25.00',
       '$199.95', '$97.99', '$21.98', '$86.99', '$24.49', '$439.99',
       '$61.99', '$17.14', '$10.70', '$399.00', '$21.99', '$29.96',
       '$6.59', '$9.99', '$69.00', '$609.99', '$41.81', '$88.99',
       '$29.73', '$11.22', '$24.95', '$159.99', '$64.85', '$139.97',
       '$189.99', '$119.99', '$59.95', '$59.99', '$76.89', '$107.99',
       '$269.99', '$23.98', '$14.99', '$129.95', '$549.99', '$74.99',
       '$289.99', '$37.99', '$16.86', '$131.99', '$26.98', '$24.98',
       '$12.99', '$42.99', '$329.99', '$134.99', '$144.99', '$104.99',
       '$209.99', '$99.00', '$15.80', '$183.64', '$179.99', '$359.99',
       '$14.55', '$288.98', '$379.99', '$259.99', '$251.99', '$16.98',
       '$67.99', '$27.86', '$249.95', '$308.00', '$229.97', '$39.95',
       '$89.00', '$649.00', '$13.99', '$31.99', '$234.89', '$799.00',
       '$369.00', '$133.99', '$94.99', '$10.15', '$10.99', '$147.99',
       '$26.99', '$242.95', '$1,299.00', '$16.99', '$399.99', '$32.43',
       '$172.99', '$11.63', '$31.44', '$10.82', '$404.00', '$151.91',
       '$55.00', '$499.00', '$215.99', '$5.41', '$54.99', '$20.18',
       '$183.29', '$78.50', '$6.99', '$9.98', '$25.98', '$899.99',
       '$8.54', '$599.00', '$151.49', '$395.99', '$759.00', '$16.09',
       '$44.99', '$569.99', '$879.99', '$284.99', '$129.00', '$429.99',
       '$198.00', '$694.99', '$28.99', '$23.74', '$83.99', '$11.99',
       '$210.00', '$120.99', '$25.54', '$70.99', '$70.92', '$117.45',
       '$54.95', '$118.00', '$67.79', '$87.99', '$49.98', '$53.90',
       '$30.72', '$439.00', '$449.99', '$57.56', '$36.37', '$24.84',
       '$58.62', '$55.99', '$699.99', '$799.99', '$355.01', '$9.26',
       '$249.00', '$549.00', '$42.00', '$349.99', '$45.99', '$13.98',
       '$309.99', '$17.26', '$174.99', '$33.59', '$7.64', '$18.00',
       '$24.41', '$203.99', '$17.12', '$89.98', '$41.99', '$29.98',
       '$153.49', '$44.80', '$154.00', '$16.29', '$11.59', '$15.19',
       '$58.50', '$999.99', '$53.99', '$299.00', '$539.99', '$145.99',
       '$56.99', '$32.32', '$279.99', '$259.00', '$21.58', '$55.04',
       '$50.99', '$489.99', '$23.79', '$569.00', '$47.99', '$30.10',
       '$8.09', '$117.99', '$1,699.99', '$51.99', '$16.56', '$16.62',
       '$129.50', '$139.99', '$49.95', '$70.00', '$132.99', '$63.99',
       '$22.78', '$11.65', '$40.99', '$198.95', '$23.48', '$13.85',
       '$499.95', '$29.00', '$12.58', '$269.00', '$139.48', '$499.99',
       '$15.89', '$319.99', '$18.61', '$137.49', '$63.50', '$2,549.00',
       '$93.95', '$124.99', '$27.97', '$109.00', '$17.29', '$90.00',
       '$155.99', '$48.63', '$144.89', '$13.49', '$419.99', '$36.48',
       '$297.77', '$347.85', '$410.99', '$22.36', '$135.99', '$356.99',
       '$297.95', '$8.38', '$119.00', '$26.89', '$23.99', '$137.99',
       '$82.60', '$206.99', '$52.99', '$409.89', '$51.89', '$79.95',
       '$999.00', '$29.95', '$389.99', '$296.99', '$140.99', '$14.66',
       '$1,399.99', '$179.95', '$8.20', '$15.75', '$274.95', '$156.40',
       '$11.19', '$354.99', '$323.99', '$199.00', '$149.97', '$106.99',
       '$38.96', '$14.50', '$1,199.99', '$23.95', '$150.00', '$22.98',
       '$647.99', '$34.90', '$57.99', '$112.99', '$26.95', '$33.56',
       '$6.54', '$82.49', '$279.00', '$21.19', '$219.00', '$210.99',
       '$36.99', '$566.99', '$139.00', '$30.70', '$1,199.00', '$42.85',
       '$127.99', '$275.00', '$863.99', '$38.88', '$114.99', '$21.77',
       '$19.70', '$434.99', '$45.08', '$48.95', '$254.99', '$248.99',
       '$599.99', '$18.39', '$68.99', '$100.60', '$71.99', '$2,799.00',
       '$52.69', '$649.99', '$699.00', '$4,299.00', '$17.59', '$459.00',
       '$195.99', '$46.99', '$597.52', '$103.99', '$2,099.99', '$109.60',
       '$43.99', '$1,099.99', '$299.95', '$1,499.00', '$33.32', '$139.95',
       '$8.94', '$729.99', '$6.68', '$164.99', '$16.59', '$29.94',
       '$224.68', '$36.27', '$34.98', '$184.99', '$339.99', '$225.00',
       '$84.95', '$4,199.00', '$54.97', '$147.91', '$81.00', '$140.79',
       '$42.40', '$208.99', '$21.20', '$224.95', '$31.26', '$117.95',
       '$10.25', '$679.95', '$125.80', '$919.99', '$128.05', '$20.69',
       '$132.61', '$8.18', '$28.46', '$2,999.00', '$30.41', '$115.90',
       '$194.99', '$521.99', '$69.95', '$289.00', '$85.00', '$187.95',
       '$30.99', '$23.38', '$56.92', '$140.00', '$177.42', '$110.00',
       '$90.99', '$109.94', '$50.98', '$24.37', '$797.99', '$48.00',
       '$2,499.95', '$17.00', '$158.99', '$185.00', '$45.00', '$116.95',
       '$60.50', '$78.49', '$109.95', '$12.79', '$36.00', '$110.46',
       '$56.65', '$99.49', '$225.99', '$84.99', '$72.99', '$26.25',
       '$116.99', '$20.26', '$262.00', '$27.42', '$971.99', '$479.00',
       '$1,499.99', '$226.99', '$127.00', '$444.99', '$277.00', '$17.10',
       '$13.68', '$24.97', '$17.49', '$75.30', '$72.60', '$101.40',
       '$349.95', '$171.99', '$118.99', '$437.97', '$1,599.00', '$171.95',
       '$350.00', '$3,399.00', '$59.90', '$372.99', '$464.07', '$100.00',
       '$29.50', '$192.00', '$20.99', '$19.97', '$102.99', '$53.00',
       '$89.95', '$525.00', '$204.69', '$21.13', '$20.94', '$149.00',
       '$339.00', '$52.00', '$47.95', '$1,299.99', '$61.20', '$311.25',
       '$104.00', '$102.81', '$164.00', '$179.00', '$271.99', '$129.97',
       '$42.80', '$54.08', '$37.11', '$608.80', '$152.99', '$326.72',
       '$21.18', '$17.98', '$265.99', '$18.05', '$93.99', '$50.68',
       '$253.00', '$3,099.00', '$259.95', '$294.00', '$9.97', '$6.38',
       '$786.80', '$42.49', '$3,599.00', '$400.99', '$13.60', '$35.00',
       '$82.50', '$81.85', '$108.99', '$9.71', '$31.02', '$274.99',
       '$719.90', '$326.99', '$144.49', '$419.00', '$597.99', '$191.02',
       '$82.99', '$114.27', '$6.48', '$8.10', '$659.00', '$120.00',
       '$389.00', '$749.99', '$1,212.64', '$448.96', '$369.99',
       '$1,799.99', '$223.50', '$333.00', '$78.59', '$159.98', '$849.99',
       '$14.15', '$162.99', '$285.00', '$42.93', '$76.00', '$91.99',
       '$29.67', '$16.15', '$34.80', '$49.00', '$12.74', '$38.69',
       '$62.34', '$37.76', '$149.95', '$7.93', '$42.97', '$244.99',
       '$31.95', '$7.92', '$1,295.00', '$368.48', '$48.97', '$20.11',
       '$519.99', '$329.95', '$2,599.00', '$829.99', '$123.49', '$319.00',
       '$113.99', '$60.99', '$19.67', '$360.00', '$33.08', '$122.95',
       '$45.17', '$889.00', '$26.78', '$40.10', '$36.11', '$324.99',
       '$869.99', '$117.02', '$168.00', '$50.39', '$21.08', '$424.99',
       '$38.25', '$218.00', '$829.95', '$1,349.00', '$239.95', '$31.29',
       '$7.99', '$975.98', '$325.86', '$84.90', '$23.50', '$49.60',
       '$145.80', '$204.99', '$8.98', '$175.95', '$31.19', '$184.00',
       '$177.00', '$521.00', '$28.30', '$10.61', '$879.00', '$10.80',
       '$190.00', '$101.64', '$28.81', '$25.55', '$78.99', '$19.66',
       '$24.08', '$14.98', '$94.95', '$81.99', '$27.00', '$169.98',
       '$54.59', '$126.99', '$157.99', '$38.00', '$35.98', '$13.28',
       '$9.50', '$23.00', '$99.98', '$125.12', '$38.05', '$12.62',
       '$109.97', '$128.99', '$333.99', '$142.99', '$166.99', '$56.86',
       '$107.30', '$684.99', '$32.41', '$16.49', '$73.99', '$9.96',
       '$9.49', '$959.94', '$220.99', '$197.95', '$148.00', '$234.99',
       '$5.95', '$1,249.99', '$53.49', '$314.60', '$7.18', '$275.99',
       '$246.99', '$399.84', '$12.84', '$12.97', '$11.91', '$41.90',
       '$32.95', '$87.78', '$394.99', '$226.00', '$24.91', '$21.95',
       '$197.99', '$1,469.00', '$352.95', '$189.00', '$66.57', '$10.49',
       '$119.95', '$39.57', '$209.95', '$130.00', '$59.00', '$238.90',
       '$19.90', '$143.95', '$40.00', '$399.90', '$7.00', '$19.80',
       '$31.88', '$51.98', '$246.00', '$8.95', '$7.86', '$359.00',
       '$308.48', '$9.80', '$16.51', '$239.00', '$298.00', '$174.95',
       '$399.95', '$176.89', '$41.67', '$322.49', '$383.99', '$229.00',
       '$84.97', '$18.98', '$204.98', '$59.59', '$77.95', '$5.48',
       '$187.98', '$329.00', '$174.21', '$161.99', '$79.00', '$14.29',
       '$409.95', '$21.50', '$74.95', '$237.71', '$29.38', '$58.99',
       '$134.95', '$81.07', '$179.90', '$528.59', '$52.50', '$98.00',
       '$126.49', '$27.07', '$354.00', '$31.66', '$52.24', '$189.95',
       '$343.34', '$15.98', '$5.49', '$220.00', '$27.33', '$167.95',
       '$8.65', '$12.60', '$429.00', '$38.99', '$29.42', '$14.91',
       '$75.51', '$18.12', '$23.96', '$82.47', '$309.00', '$4.95',
       '$26.66', '$64.95', '$167.70', '$495.00', '$729.00', '$52.49',
       '$143.99', '$263.50', '$18.95', '$202.00', '$22.61', '$7.19',
       '$8.89', '$154.99', '$629.00', '$28.29', '$50.00', '$49.59',
       '$36.44', '$669.99', '$25.63', '$9.39', '$123.37', '$8.92',
       '$495.96', '$10.64', '$185.99', '$194.95', '$21.60', '$439.95',
       '$20.82', '$14.24', '$109.34', '$579.99', '$309.95', '$200.00',
       '$508.00', '$17.78', '$24.86', '$13.16', '$27.95', '$24.75',
       '$41.95', '$34.95', '$1,049.00', '$469.99', '$39.18', '$224.99',
       '$313.99', '$98.99', '$66.00', '$20.98', '$42.50', '$116.00',
       '$199.39', '$138.99', '$52.94', '$79.02', '$116.64', '$22.00',
       '$50.37', '$74.93', '$33.90', '$122.00', '$85.99', '$226.51',
       '$21.00', '$16.61', '$25.49', '$66.01', '$14.97', '$26.81',
       '$13.51', '$66.22', '$48.62', '$283.99', '$23.26', '$569.95',
       '$464.40', '$609.00', '$15.96', '$2,899.00', '$16.97', '$9.10',
       '$21.39', '$599.95', '$950.43'], dtype=object)

In [155]:
df1['listed_price'] = df1['listed_price'].astype(str).str.lower()

df1['listed_price'] = df1['listed_price'].str.extract(r'(\d+\.?\d*)')
df1['listed_price'] = pd.to_numeric(df1['listed_price'] , errors = 'coerce').astype(float).round(4)

df1['listed_price'] = df1['listed_price'].fillna(df1['listed_price'].mean())

In [156]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32233 entries, 0 to 42674
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    32233 non-null  float64
 1   number_of_reviews         32140 non-null  object
 2   bought_in_last_month      32233 non-null  Int64
 3   current/discounted_price  32233 non-null  float64
 4   price_on_variant          32233 non-null  float64
 5   listed_price              32233 non-null  float64
 6   is_best_seller            32233 non-null  int64
 7   is_sponsored              32233 non-null  int64
 8   is_couponed               32233 non-null  int64
dtypes: Int64(1), float64(4), int64(3), object(1)
memory usage: 3.5+ MB

number of reviews

In [157]:
df1['number_of_reviews'] = df1['number_of_reviews'].replace({',' ,''})
df1['number_of_reviews'] = pd.to_numeric(df1['number_of_reviews'] , errors = 'coerce').astype(float).round(4)

df1['number_of_reviews'] = df1['number_of_reviews'].fillna(df1['number_of_reviews'].mean())

/tmp/ipykernel_15028/2446318984.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df1['number_of_reviews'] = df1['number_of_reviews'].replace({',' ,''})

In [158]:
df1['number_of_reviews'].unique()

array([375.        , 266.15003093, 152.        , 450.        ,
       744.        , 885.        , 815.        , 154.        ,
       598.        ,  69.        , 549.        ,  65.        ,
       496.        , 723.        , 743.        , 297.        ,
       423.        , 647.        , 590.        , 198.        ,
       510.        , 490.        , 526.        , 172.        ,
       260.        , 812.        , 378.        , 380.        ,
       130.        , 196.        , 866.        , 264.        ,
       971.        , 391.        , 340.        , 187.        ,
       768.        , 620.        , 457.        , 562.        ,
       591.        , 796.        , 757.        , 273.        ,
       451.        , 579.        , 658.        ,  63.        ,
       293.        , 360.        , 191.        , 960.        ,
       454.        , 805.        , 894.        , 465.        ,
       447.        , 265.        , 657.        , 927.        ,
        94.        ,  57.        , 394.        , 281.        ,
       581.        , 343.        , 834.        , 519.        ,
       181.        , 762.        , 925.        , 412.        ,
       604.        , 128.        , 413.        , 175.        ,
       813.        , 379.        , 646.        , 740.        ,
       491.        , 836.        , 115.        , 158.        ,
       125.        , 816.        , 141.        , 124.        ,
         3.        , 759.        ,  67.        , 550.        ,
       615.        , 387.        , 208.        , 520.        ,
       478.        , 787.        , 791.        , 625.        ,
       119.        , 553.        , 114.        , 685.        ,
       390.        , 460.        , 393.        , 384.        ,
       305.        , 628.        , 570.        , 924.        ,
       872.        , 283.        , 561.        , 416.        ,
       776.        , 576.        , 302.        , 765.        ,
        37.        ,  83.        , 645.        , 959.        ,
        70.        , 929.        , 634.        , 288.        ,
       215.        , 770.        , 237.        , 477.        ,
       728.        , 304.        , 366.        , 826.        ,
       165.        ,  64.        , 738.        , 408.        ,
       668.        , 919.        ,  44.        , 170.        ,
       422.        , 691.        ,   8.        ,  85.        ,
        77.        , 755.        ,  91.        , 664.        ,
       967.        , 623.        , 449.        , 135.        ,
        59.        , 155.        ,  20.        , 748.        ,
       515.        ,  97.        , 763.        , 650.        ,
       827.        , 178.        , 986.        , 299.        ,
        74.        , 548.        , 329.        , 621.        ,
       513.        ,  21.        , 501.        , 183.        ,
       472.        , 871.        , 295.        , 382.        ,
       134.        , 112.        , 359.        , 136.        ,
       344.        , 227.        , 350.        , 213.        ,
       376.        , 290.        , 289.        , 275.        ,
       254.        , 419.        ,  45.        , 330.        ,
       949.        , 603.        , 633.        , 618.        ,
       747.        , 420.        , 975.        ,  22.        ,
       831.        , 521.        , 825.        , 325.        ,
       453.        , 544.        , 809.        , 341.        ,
       798.        , 401.        ,  87.        , 328.        ,
       188.        , 996.        , 629.        , 383.        ,
       984.        , 132.        , 179.        , 220.        ,
        32.        , 251.        , 673.        , 795.        ,
       542.        , 758.        , 153.        ,  30.        ,
       910.        , 282.        , 829.        , 830.        ,
       525.        , 156.        , 180.        , 771.        ,
       512.        , 203.        , 353.        , 844.        ,
       143.        , 481.        , 781.        , 310.        ,
       902.        ,   9.        , 386.        , 348.        ,
       291.        , 624.        ,  99.        , 766.        ,
        68.        , 313.        , 963.        , 216.        ,
       880.        , 992.        , 214.        , 627.        ,
       174.        ,  35.        ,  66.        , 186.        ,
       224.        , 708.        ,  51.        ,  95.        ,
        12.        , 426.        , 923.        , 410.        ,
       822.        , 865.        , 209.        , 568.        ,
       239.        , 292.        , 774.        , 284.        ,
       895.        , 182.        , 583.        , 151.        ,
       326.        , 606.        , 527.        ,  14.        ,
       312.        , 122.        ,  73.        , 953.        ,
       662.        , 404.        ,  46.        ,   4.        ,
       437.        , 230.        , 210.        , 374.        ,
       240.        , 139.        ,  15.        , 661.        ,
       475.        ,  38.        , 217.        , 613.        ,
       445.        ,   1.        , 632.        , 146.        ,
       531.        ,  84.        , 857.        , 592.        ,
       678.        , 694.        , 523.        , 381.        ,
       701.        , 463.        ,  56.        ,  41.        ,
       166.        , 147.        , 443.        , 908.        ,
       109.        , 400.        , 369.        ,  19.        ,
       793.        , 672.        ,  52.        , 219.        ,
        33.        ,  81.        , 764.        , 318.        ,
       659.        , 238.        , 934.        , 331.        ,
       601.        ,  72.        , 582.        , 105.        ,
       157.        , 873.        , 204.        ,  55.        ,
       131.        , 397.        , 377.        , 316.        ,
       702.        ,  26.        , 176.        , 600.        ,
       779.        , 987.        , 840.        , 411.        ,
       266.        , 185.        , 246.        , 357.        ,
        58.        , 127.        , 991.        , 300.        ,
       914.        ,  31.        , 110.        ,  39.        ,
       113.        , 736.        , 726.        , 828.        ,
       269.        ,   5.        ,  76.        , 850.        ,
       278.        , 541.        , 117.        , 245.        ,
       324.        ,  75.        , 994.        , 229.        ,
       197.        ,  61.        , 788.        , 247.        ,
       639.        , 101.        ,   7.        ,  24.        ,
       195.        , 407.        , 234.        ,  54.        ,
       750.        , 732.        , 149.        , 660.        ,
       498.        , 746.        , 161.        , 441.        ,
       442.        , 951.        , 999.        , 522.        ,
       321.        , 785.        , 303.        , 528.        ,
       309.        , 425.        , 577.        , 571.        ,
       307.        , 405.        ,  11.        , 767.        ,
       948.        , 918.        , 538.        ,  36.        ,
       559.        , 414.        , 630.        , 169.        ,
       617.        , 160.        , 262.        , 361.        ,
       674.        , 656.        , 724.        , 429.        ,
       930.        , 875.        , 995.        , 932.        ,
         2.        , 140.        ,  43.        , 294.        ,
       584.        ,  78.        , 259.        , 610.        ,
       395.        , 573.        , 189.        ,  40.        ,
        88.        , 244.        , 938.        , 565.        ,
       100.        , 111.        , 263.        , 640.        ,
       503.        ,  62.        , 355.        , 917.        ,
       506.        , 556.        , 823.        , 532.        ,
       116.        , 118.        , 753.        , 856.        ,
        47.        , 406.        , 769.        , 921.        ,
       619.        , 735.        , 306.        , 257.        ,
        34.        , 682.        , 317.        ,  13.        ,
       200.        ,  42.        , 268.        ,  96.        ,
       551.        , 802.        , 228.        , 351.        ,
        80.        , 319.        , 848.        , 456.        ,
       983.        , 593.        , 839.        , 248.        ,
       666.        , 782.        , 980.        , 540.        ,
       133.        , 741.        , 272.        , 202.        ,
       837.        ,  50.        , 194.        , 631.        ,
        98.        , 468.        , 396.        , 126.        ,
       473.        , 271.        , 327.        , 320.        ,
       409.        , 543.        , 707.        , 171.        ,
        53.        , 859.        , 504.        , 462.        ,
       104.        , 421.        , 884.        ,  86.        ,
       167.        , 554.        ,  18.        , 958.        ,
         6.        , 898.        , 223.        , 832.        ,
       761.        , 714.        , 427.        , 731.        ,
       697.        , 869.        , 428.        , 683.        ,
       211.        , 233.        , 362.        ,  93.        ,
       790.        , 599.        , 255.        , 906.        ,
       944.        , 402.        , 388.        , 720.        ,
       681.        , 652.        , 778.        , 772.        ,
       663.        , 201.        , 578.        , 296.        ,
       225.        ,  23.        ,  17.        , 482.        ,
       177.        , 973.        , 277.        , 654.        ,
        49.        , 534.        , 192.        , 846.        ,
       332.        , 150.        , 452.        , 193.        ,
       686.        ,  79.        , 667.        , 301.        ,
        16.        , 103.        , 882.        , 575.        ,
       690.        , 145.        , 212.        , 236.        ,
       789.        , 356.        , 207.        ,  92.        ,
       912.        , 389.        , 572.        , 286.        ,
        10.        , 687.        ,  25.        , 120.        ,
       560.        , 469.        ,  48.        , 285.        ,
       206.        , 692.        , 123.        , 440.        ,
       497.        , 142.        , 883.        , 346.        ,
       596.        , 648.        , 494.        , 162.        ,
       518.        , 403.        , 430.        , 287.        ,
       719.        , 833.        , 566.        , 138.        ,
       878.        , 363.        , 874.        , 552.        ,
       974.        , 436.        , 252.        ,  89.        ,
        27.        , 962.        , 250.        , 480.        ,
       349.        , 585.        , 516.        , 308.        ,
       824.        , 467.        , 232.        , 274.        ,
       385.        , 339.        , 704.        , 942.        ,
       241.        ,  28.        , 976.        , 364.        ,
       985.        , 108.        , 597.        , 998.        ,
       675.        , 199.        , 439.        , 614.        ,
       864.        ,  82.        , 626.        , 315.        ,
       270.        , 718.        , 164.        ,  90.        ,
       335.        , 458.        , 861.        , 435.        ,
       990.        , 609.        , 760.        , 893.        ,
       137.        , 936.        , 218.        , 602.        ,
       819.        , 855.        , 489.        , 163.        ,
       911.        , 253.        , 279.        , 336.        ,
       989.        ,  29.        , 777.        , 459.        ,
        60.        , 372.        , 818.        , 879.        ,
       792.        , 322.        , 877.        , 680.        ,
       231.        , 502.        , 636.        , 499.        ,
       107.        , 333.        , 845.        , 711.        ,
       907.        , 190.        , 729.        , 529.        ,
       535.        ,  71.        , 221.        , 780.        ,
       342.        , 173.        , 129.        , 168.        ,
       725.        , 905.        , 106.        , 887.        ,
       684.        , 886.        , 249.        , 546.        ,
       699.        , 345.        , 713.        , 370.        ,
       483.        , 226.        , 868.        , 649.        ,
       368.        , 892.        , 539.        , 867.        ,
       957.        , 371.        , 721.        , 121.        ,
       432.        , 696.        , 545.        , 444.        ,
       588.        , 261.        , 969.        , 418.        ,
       184.        , 495.        , 706.        , 695.        ,
       956.        , 712.        , 679.        , 486.        ,
       509.        , 876.        , 783.        , 941.        ,
       810.        , 904.        , 900.        , 669.        ,
       580.        , 637.        , 607.        , 586.        ,
       347.        , 461.        , 524.        , 800.        ,
       338.        , 256.        , 352.        , 853.        ,
       594.        , 801.        , 488.        , 148.        ,
       860.        , 487.        , 842.        , 799.        ,
       235.        , 484.        , 933.        , 517.        ,
       655.        , 979.        , 433.        , 814.        ,
       733.        , 730.        , 358.        , 446.        ,
       940.        , 982.        , 688.        , 367.        ,
       820.        , 399.        , 939.        , 756.        ,
       709.        , 981.        , 563.        , 665.        ,
       222.        , 703.        , 323.        , 641.        ,
       891.        , 567.        , 298.        , 803.        ,
       258.        , 946.        , 841.        , 354.        ,
       897.        , 988.        , 638.        , 415.        ,
       280.        , 693.        , 945.        , 276.        ,
       448.        , 950.        , 671.        , 965.        ,
       476.        , 311.        , 903.        , 558.        ,
       500.        , 243.        , 889.        , 589.        ,
       507.        , 574.        , 644.        , 786.        ,
       102.        , 373.        , 752.        , 564.        ,
       514.        , 916.        , 806.        , 997.        ,
       881.        , 485.        , 466.        , 863.        ,
       966.        , 677.        , 854.        , 616.        ,
       608.        , 913.        , 642.        , 611.        ,
       676.        , 471.        , 595.        , 159.        ,
       972.        , 734.        , 775.        , 727.        ,
       474.        , 537.        , 937.        , 555.        ,
       530.        , 749.        , 314.        , 424.        ,
       392.        , 205.        , 267.        , 511.        ,
       807.        , 431.        , 612.        , 508.        ,
       843.        , 890.        ])

In [159]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32233 entries, 0 to 42674
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    32233 non-null  float64
 1   number_of_reviews         32233 non-null  float64
 2   bought_in_last_month      32233 non-null  Int64
 3   current/discounted_price  32233 non-null  float64
 4   price_on_variant          32233 non-null  float64
 5   listed_price              32233 non-null  float64
 6   is_best_seller            32233 non-null  int64
 7   is_sponsored              32233 non-null  int64
 8   is_couponed               32233 non-null  int64
dtypes: Int64(1), float64(5), int64(3)
memory usage: 3.5 MB

In [160]:
from sklearn.model_selection import train_test_split

In [161]:
X = df1.drop(columns = ['rating' , 'number_of_reviews' ,
'price_on_variant','current/discounted_price', 'bought_in_last_month',
'listed_price'  , 'is_sponsored' , 'is_couponed'
 ])

In [162]:
Y = df1['is_best_seller']

In [163]:
X_train ,X_test,Y_train ,Y_test = train_test_split(X ,Y ,test_size = 0.2 , random_state = 42)

In [164]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_resampled, Y_resampled = sm.fit_resample(X_train , Y_train)

X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_resampled ,
Y_resampled,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train_new)
scaled_X_test = scaler.transform(X_test_new)

In [176]:
from sklearn.linear_model import SGDRegressor

In [177]:
model = SGDRegressor(max_iter=1000, learning_rate='invscaling')

In [183]:
model.fit(scaled_X_train , y_train_new)

SGDRegressor()

In [184]:
pred = model.predict(scaled_X_test)

In [185]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import numpy as np

print("MAE:", mean_absolute_error(y_test_new, pred))

print("MSE:", mean_squared_error(y_test_new, pred))

print("RMSE:", np.sqrt(mean_squared_error(y_test_new, pred)))

print("R2:", r2_score(y_test_new, pred))

MAE: 0.0002224869146851814
MSE: 6.650256031742117e-08
RMSE: 0.0002578809033593243
R2: 0.9999999900611843